### ISSUE TITLE
Default to Kotlin, Keep Java in a Branch

### ISSUE THREAD

**Issue by weverb2** [madebyatomicrobot/android-starter-project#47]
Taking inspiration from: https://github.com/googlesamples/android-topeka

**Comment by patrickhammond** [comment]
I was thinking about that at 1am last night. Was about to force push the changes to rename the branches but decided to hold off until I was thinking more clearly.

Still pretty sure that is what will happen.

**Comment by patrickhammond** [comment]
**As of Sept 17, 2017, all new Android projects moving forward will default to Kotlin as the language of choice.**

Rough metrics:
- APK size between Java and Kotlin builds are the same.
- The Kotlin APK actually has **less** methods. I am guessing that is because we are using the build int Parcelable support in Kotlin 1.4-3 vs using Parceler in the Java project.
- Build time between Java and Kotlin builds are the same.
- Lines of code between the latest `master` and `java` HEAD commits at the time of this writing: Java 2369, Kotlin 1908 (20% less than Java). Both counted from `app/src` using `find . -name '*.kt' | xargs wc -l`, extension updated appropriately). Also note that there is a little extra stuff in the Kotlin version that never got ported over to Java.
